Repository Typeform/embed, pull requests merged in 2021-12, with the labels that each got.

#427 docs(DIST-1216): Update readme with breaking changes info's
  README.md
Labels: size/xs

#425 docs(DIST-1216): Update readme with breaking change notice
  README.md
Labels: size/xs

#428 feat(DIST-582): Widget lazy loading
  packages/demo-html/public/widget-lazy-html.html
  packages/embed/README.md
  packages/embed/src/css/widget.scss
  packages/embed/src/factories/create-widget/create-widget.ts
  packages/embed/src/factories/create-widget/widget-options.ts
  packages/embed/src/initializers/build-options-from-attributes.spec.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
  packages/embed/src/utils/index.ts
  packages/embed/src/utils/lazy-init.spec.ts
  packages/embed/src/utils/lazy-init.ts
Labels: size/m

#429 feat(DIST-664): Add option to keep session
  package.json
  packages/demo-html/public/keep-session-html.html
  packages/embed/README.md
  packages/embed/e2e/spec/functional/keep-session.spec.ts
  packages/embed/src/base/base-options.ts
  packages/embed/src/base/index.ts
  packages/embed/src/base/modal-window-options.ts
  packages/embed/src/css/widget.scss
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-popover/popover-options.ts
  packages/embed/src/factories/create-popup/create-popup.ts
  packages/embed/src/factories/create-popup/popup-options.ts
  packages/embed/src/factories/create-sidetab/create-sidetab.ts
  packages/embed/src/factories/create-sidetab/sidetab-options.ts
  packages/embed/src/factories/create-slider/create-slider.ts
  packages/embed/src/factories/create-slider/slider-options.ts
  packages/embed/src/factories/create-widget/create-widget.ts
  packages/embed/src/factories/create-widget/widget-options.ts
  packages/embed/src/initializers/build-options-from-attributes.spec.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
  packages/embed/src/utils/index.ts
  packages/embed/src/utils/is-open.spec.ts
  packages/embed/src/utils/is-open.ts
  yarn.lock
Labels: size/m

#432 fix(DIST-1150): Update HTTP warning logic
  packages/embed/src/utils/create-http-warning-banner.ts
Labels: size/xs

#434 fix(TYP-6098): Remove warning for non-HTTPS websites
  packages/embed/src/css/includes/_http-banner.scss
  packages/embed/src/css/popover.scss
  packages/embed/src/css/popup.scss
  packages/embed/src/css/sidetab.scss
  packages/embed/src/css/slider.scss
  packages/embed/src/css/widget.scss
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-popup/create-popup.ts
  packages/embed/src/factories/create-sidetab/create-sidetab.ts
  packages/embed/src/factories/create-slider/create-slider.ts
  packages/embed/src/factories/create-widget/elements/build-widget.ts
  packages/embed/src/utils/create-http-warning-banner.spec.ts
  packages/embed/src/utils/create-http-warning-banner.ts
  packages/embed/src/utils/index.ts
Labels: size/m

#433 chore(DIST-1119): Add docs from developer portal
  .github/workflows/trigger-external-update.yml
  docs/callbacks.md
  docs/configuration.md
  docs/contributing.md
  docs/custom-embed.md
  docs/hidden-fields.md
  docs/index.md
  docs/inline.md
  docs/modal.md
  docs/native-mobile-apps.md
  docs/react.md
  docs/vanilla.md
Labels: size/l

#435 chore(DIST-1119): Update docs on mobile apps
  docs/index.md
  docs/mobile-apps.md
  packages/embed/README.md
Labels: size/s
