Repository Typeform/embed, pull requests merged in 2021-07, with the labels that each got.

#281 chore(DIST-1066): Release to github
  packages/embed-react/package.json
Labels: size/xs

#278 fix(DIST-1042): Add disable submission to fake welcome screen on mobile
  src/core/views/widget.js
  src/core/views/widget.spec.js
Labels: size/xs

#283 fix(DIST-1066): Github deploy
  packages/embed-react/package.json
Labels: size/xs

#279 feat(DIST-704): Add shareGoogleAnalyticsInstance option
  packages/demo-html/public/widget-html.html
  packages/embed/README.md
  packages/embed/src/base/url-options.ts
  packages/embed/src/initializers/build-options-from-attributes.spec.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
  packages/embed/src/utils/build-iframe-src.ts
  packages/embed/src/utils/create-iframe/create-iframe.ts
  packages/embed/src/utils/create-iframe/get-form-event-handler.ts
  packages/embed/src/utils/index.ts
  packages/embed/src/utils/setup-google-analytics-instance.spec.ts
  packages/embed/src/utils/setup-google-analytics-instance.ts
Labels: size/m

#285 feat(DIST-1002): Auto close
  packages/demo-html/public/autoclose.html
  packages/embed/e2e/spec/functional/auto-close.spec.ts
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-popover/popover-options.ts
  packages/embed/src/factories/create-popup/create-popup.spec.ts
  packages/embed/src/factories/create-popup/create-popup.ts
  packages/embed/src/factories/create-popup/popup-options.ts
  packages/embed/src/factories/create-sidetab/create-sidetab.ts
  packages/embed/src/factories/create-sidetab/sidetab-options.ts
  packages/embed/src/factories/create-slider/create-slider.spec.ts
  packages/embed/src/factories/create-slider/create-slider.ts
  packages/embed/src/factories/create-slider/slider-options.ts
  packages/embed/src/factories/create-widget/create-widget.spec.ts
  packages/embed/src/factories/create-widget/create-widget.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
  packages/embed/src/utils/create-iframe/create-iframe.spec.ts
  packages/embed/src/utils/create-iframe/create-iframe.ts
  packages/embed/src/utils/create-iframe/get-form-event-handler.ts
  packages/embed/src/utils/index.ts
  packages/embed/src/utils/load-options-from-attributes.spec.ts
  packages/embed/src/utils/load-options-from-attributes.ts
  packages/embed/src/utils/set-auto-close.spec.ts
  packages/embed/src/utils/set-auto-close.ts
Labels: size/m

#289 chore(DIST-1002): Update readme
  packages/embed/README.md
Labels: size/s

#290 fix(DIST-1042): Allow embedding inline widget on mobile
  src/core/views/widget.js
  src/core/views/widget.spec.js
Labels: size/s

#291 fix(DIST-1068): Image icon size fix
  packages/demo-html/public/popup-html.html
  packages/embed/src/factories/create-sidetab/create-sidetab.ts
Labels: size/xs

#292 feat(DIST-1068): Force touch option
  packages/embed/src/base/url-options.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
  packages/embed/src/utils/build-iframe-src.ts
Labels: size/xs

#294 feat(DIST-1005): Close embed on Keyboard event
  packages/embed/e2e/spec/functional/close-on-keyboard.spec.ts
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-popup/create-popup.ts
  packages/embed/src/factories/create-sidetab/create-sidetab.ts
  packages/embed/src/factories/create-slider/create-slider.ts
  packages/embed/src/utils/create-iframe/create-iframe.ts
  packages/embed/src/utils/create-iframe/index.ts
  packages/embed/src/utils/create-iframe/setup-custom-keyboard-close.ts
Labels: size/s

#297 feat(DIST-1089): Full screen on mobile
  packages/embed/e2e/spec/functional/popover.spec.ts
  packages/embed/e2e/spec/functional/sidetab.spec.ts
  packages/embed/e2e/spec/visual/mobile.spec.ts
  packages/embed/src/css/includes/_close.scss
  packages/embed/src/css/popover.scss
  packages/embed/src/css/popup.scss
  packages/embed/src/css/sidetab.scss
  packages/embed/src/css/slider.scss
  packages/embed/src/factories/create-popover/create-popover.spec.ts
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-sidetab/create-sidetab.spec.ts
  packages/embed/src/factories/create-sidetab/create-sidetab.ts
Labels: size/m

#299 fix(DIST-1089): Use important for width and height
  packages/embed/src/css/includes/_fullsize.scss
  packages/embed/src/css/popover.scss
  packages/embed/src/css/popup.scss
  packages/embed/src/css/sidetab.scss
  packages/embed/src/css/slider.scss
Labels: size/s

#300 feat(DIST-123): Add id as param for embed demo
  packages/demo-nextjs/pages/_app.js
  packages/demo-nextjs/pages/index.js
  packages/demo-nextjs/pages/popover.js
  packages/demo-nextjs/pages/popup.js
  packages/demo-nextjs/pages/sidetab.js
  packages/demo-nextjs/pages/slider.js
  packages/demo-nextjs/pages/vanilla.js
Labels: size/s

#296 fix(DIST-1112): Update custom icon to fit button size
  packages/embed/src/css/popover.scss
  packages/embed/src/factories/create-popover/create-popover.ts
Labels: size/xs
