Repository Typeform/embed, pull requests merged in 2021-06, with the labels that each got.

#248 feat(DIST-923): Add notification dot to chat
  packages/demo-html/public/chat.html
  packages/demo-html/public/popover-html.html
  packages/embed/e2e/spec/functional/chat.spec.ts
  packages/embed/e2e/spec/visual/chat.spec.ts
  packages/embed/src/css/popover.scss
  packages/embed/src/factories/create-popover/create-popover.spec.ts
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-popover/popover-options.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
Labels: size/m

#253 fix(DIST-923): Fix notification dot functionality
  packages/demo-html/public/chat.html
  packages/embed/README.md
  packages/embed/src/css/popover.scss
  packages/embed/src/factories/create-popover/create-popover.spec.ts
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-popover/notification-days.spec.ts
  packages/embed/src/factories/create-popover/notification-days.ts
Labels: size/m

#254 fix(DIST-923): Show notification dot in sandbox mode regardless of hide until time
  packages/demo-html/public/popover-html.html
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-popover/notification-days.spec.ts
  packages/embed/src/factories/create-popover/notification-days.ts
Labels: size/s

#257 feat(WEB-1974): Disabling scroll for popup and slider
  packages/embed/src/factories/create-popup/create-popup.spec.ts
  packages/embed/src/factories/create-popup/create-popup.ts
  packages/embed/src/factories/create-slider/create-slider.spec.ts
  packages/embed/src/factories/create-slider/create-slider.ts
Labels: size/s

#259 chore(DIST-977): Master fail notification
  .github/workflows/release.yml
Labels: size/xs

#258 chore(DIST-977): Master build fail notification
  .github/workflows/release.yml
Labels: size/xs

#262 chore(DIST-978): Yarn cache
  .github/workflows/pull-request.yml
Labels: size/m

#266 fix(DIST-779): Update dependencies
  package.json
  packages/demo-nextjs/package.json
  packages/demo-react/package.json
  packages/demo-webpack/package.json
  packages/embed-react/package.json
  yarn.lock
Labels: size/s

#267 chore(DIST-779): Update READMEs and demos
  README.md
  packages/demo-nextjs/README.md
  packages/demo-nextjs/components/flex.js
  packages/demo-nextjs/package.json
  packages/demo-nextjs/pages/_app.js
  packages/demo-nextjs/pages/sidetab.js
  packages/demo-nextjs/pages/vanilla.js
  packages/demo-react/README.md
  packages/embed-react/README.md
  packages/embed/README.md
Labels: size/m

#268 chore: [DIST-1037] Added prettier config to the root
  .eslintrc.js
  .github/workflows/ci-standard-checks.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/pull-request-next.yml
  .github/workflows/release.yml
  .gitleaks.toml
  applitools.config.js
  commitlint.config.js
  lerna.json
  package.json
  packages/demo-html/CHANGELOG.md
  packages/demo-html/README.md
  packages/demo-html/public/behavioral-html/exit-html.html
  packages/demo-html/public/behavioral-html/scroll-html.html
  packages/demo-html/public/behavioral-html/time-html.html
  packages/demo-html/public/behavioral-js/exit-js.html
  packages/demo-html/public/behavioral-js/load-js.html
  packages/demo-html/public/behavioral-js/scroll-js.html
  packages/demo-html/public/behavioral-js/time-js.html
  packages/demo-html/public/callbacks.html
  packages/demo-html/public/chat.html
  packages/demo-html/public/popover-js.html
  packages/demo-html/public/popup-js.html
  packages/demo-html/public/sidetab-js.html
  packages/demo-html/public/slider-js.html
  packages/demo-html/public/widget-js.html
  packages/demo-html/public/widget-sandbox.html
  packages/demo-nextjs/README.md
  packages/demo-nextjs/components/flex.js
  packages/demo-nextjs/components/sparkle.js
  packages/demo-nextjs/pages/_app.js
  packages/demo-nextjs/pages/index.js
  packages/demo-nextjs/pages/popover.js
  packages/demo-nextjs/pages/popup.js
  packages/demo-nextjs/pages/sidetab.js
  packages/demo-nextjs/pages/slider.js
  packages/demo-nextjs/pages/vanilla.js
  packages/demo-react/CHANGELOG.md
  packages/demo-react/README.md
  packages/demo-react/src/App.js
  packages/demo-react/src/index.css
  packages/demo-react/src/index.js
  packages/demo-webpack/README.md
  packages/demo-webpack/src/index.js
  packages/demo-webpack/src/make-navigation.js
  packages/demo-webpack/src/make-page.js
  packages/demo-webpack/webpack.config.js
  packages/embed-react/CHANGELOG.md
  packages/embed/CHANGELOG.md
Labels: size/xl
