Repository Typeform/embed, pull requests merged in 2021-10, with the labels that each got.

#396 feat(DIST-1237): Added workflow to trigger embed demos update
  .github/workflows/trigger-demos-update.yml
Labels: size/s

#397 feat(DIST-1237): Update trigger-demos-update.yml
  .github/workflows/trigger-demos-update.yml
Labels: size/xs

#398 chore(DIST-1237): Update README docs
  packages/embed/README.md
Labels: size/s

#399 fix(TYP-5406): Fix shareGaInstance feature
  .huskyrc
  packages/demo-html/public/widget-html.html
  packages/embed/README.md
  packages/embed/src/base/url-options.ts
  packages/embed/src/initializers/build-options-from-attributes.spec.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
  packages/embed/src/utils/create-iframe/create-iframe.ts
  packages/embed/src/utils/load-options-from-attributes.spec.ts
  packages/embed/src/utils/load-options-from-attributes.ts
  packages/embed/src/utils/setup-google-analytics-instance.spec.ts
  packages/embed/src/utils/setup-google-analytics-instance.ts
Labels: size/m
