Repository Typeform/embed, pull requests merged in 2021-08, with the labels that each got.

#302 feat(DIST-1126): Allow reloading and loading snippets in page
  packages/demo-html/public/reload-event.html
  packages/embed/src/browser.ts
  packages/embed/src/initializers/initialize-popovers.ts
  packages/embed/src/initializers/initialize-popups.ts
  packages/embed/src/initializers/initialize-sidetabs.ts
  packages/embed/src/initializers/initialize-sliders.ts
  packages/embed/src/initializers/initialize-widgets.ts
  packages/embed/src/initializers/initialize.ts
Labels: size/m

#307 fix(DIST-1138): Custom icon aspect ratio
  packages/embed/src/css/popover.scss
  packages/embed/src/factories/create-popover/create-popover.ts
Labels: size/s

#308 chore(DIST-1130): Update readme and add tests
  .gitleaks.toml
  packages/demo-html/public/widget-html.html
  packages/embed/README.md
  packages/embed/e2e/spec/functional/reload.spec.ts
Labels: size/s

#303 fix(DIST-1112): Fix custom icon on mobile
  packages/demo-html/public/chat.html
  packages/embed/src/css/popover.scss
Labels: size/s

#309 chore(DIST-1090): Update README with info about inlineOnMobile
  packages/embed/README.md
Labels: size/xs

#310 fix(DIST-1131): Allow comas in hidden fields
  packages/embed/README.md
  packages/embed/src/utils/load-options-from-attributes.spec.ts
  packages/embed/src/utils/load-options-from-attributes.ts
Labels: size/s

#312 fix(DIST-1068): Force fullscreen when force touch enabled
  packages/embed/src/factories/create-widget/create-widget.ts
Labels: size/xs

#316 fix(DIST-1127): Fix text colors on bright backgrounds
  packages/embed/README.md
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-sidetab/create-sidetab.ts
  packages/embed/src/utils/get-text-color.spec.ts
  packages/embed/src/utils/get-text-color.ts
  packages/embed/src/utils/hex-rgb.spec.ts
  packages/embed/src/utils/hex-rgb.ts
  packages/embed/src/utils/index.ts
Labels: size/m

#320 fix(DIST-1183): Load embed elements on lib load
  packages/demo-html/public/behavioral-html/exit-html.html
  packages/demo-html/public/client-side.html
  packages/embed/e2e/spec/functional/client-side.spec.ts
  packages/embed/src/browser.ts
Labels: size/s

#321 chore(DIST-1165): Dependabot interval change
  .github/dependabot.yml
Labels: size/s

#317 fix(DIST-1161): Fix height on mobile
  packages/embed/src/css/includes/_fullsize.scss
Labels: size/xs

#367 chore(DIST-1197): Update dependabot config to @typeform/* deps only
  .github/dependabot.yml
Labels: size/xs

#368 fix(DIST-1199): Enable submission for fake welcome screen on mobile
  src/core/views/widget.js
  src/core/views/widget.spec.js
Labels: size/xs

#369 fix(DIST-1195): Load embed snippets after the page has loaded
  packages/demo-html/public/callbacks.html
  packages/demo-html/public/client-side.html
  packages/embed/src/browser.ts
Labels: size/s

#371 fix(DIST-1220): Set correct z-index for fullscreen widget on mobile
  packages/demo-html/public/popover-js.html
  packages/demo-html/public/popup-html.html
  packages/demo-html/public/widget-html.html
  packages/demo-html/public/widget-js.html
  packages/embed/README.md
  packages/embed/src/css/widget.scss
Labels: size/s

#372 fix(DIST-1233): Fix data-tf-disable-auto-focus attribute
  packages/embed/README.md
  packages/embed/src/initializers/build-options-from-attributes.ts
Labels: size/xs

#373 feat(DIST-1234): Customizable html for PopupButton
  packages/embed-react/src/components/make-button-component.tsx
Labels: size/s
