Repository Typeform/embed, pull requests merged in 2021-09, with the labels that each got.

#375 chore(DIST-1229): Slack action changed
  .github/workflows/release.yml
Labels: size/xs

#385 chore(DIST-1242): Add embed sdk survey
  README.md
Labels: size/xs

#386 chore(DIST-1250): Add onSubmit param deprecation alert
  packages/embed/src/base/actionable-options.ts
Labels: size/xs

#389 feat(DIST-1217): Add tracking as url option
  packages/demo-html/public/widget-html.html
  packages/demo-nextjs/pages/vanilla.js
  packages/embed/README.md
  packages/embed/src/base/url-options.ts
  packages/embed/src/initializers/build-options-from-attributes.spec.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
  packages/embed/src/utils/build-iframe-src.ts
  packages/embed/src/utils/build-iframe.src.spec.ts
Labels: size/m

#383 fix(DIST-1269): Pass props to button component
  packages/embed-react/src/components/make-button-component.spec.tsx
  packages/embed-react/src/components/make-button-component.tsx
Labels: size/s

#393 feat(DIST-1303): Updated dependabot config
  .github/dependabot.yml
Labels: size/s
