Repository Typeform/embed, pull requests merged in 2021-11, with the labels that each got.

#412 feat(DIST-1336): Show CSP warning for http users
  packages/embed/src/css/includes/_http-banner.scss
  packages/embed/src/css/popover.scss
  packages/embed/src/css/popup.scss
  packages/embed/src/css/sidetab.scss
  packages/embed/src/css/slider.scss
  packages/embed/src/css/widget.scss
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-popup/create-popup.ts
  packages/embed/src/factories/create-sidetab/create-sidetab.ts
  packages/embed/src/factories/create-slider/create-slider.ts
  packages/embed/src/factories/create-widget/elements/build-widget.ts
  packages/embed/src/utils/create-http-warning-banner.ts
  packages/embed/src/utils/index.ts
Labels: size/s

#414 chore(DIST-1416): Update demo forms
  packages/demo-html/public/autoclose.html
  packages/demo-html/public/behavioral-html/exit-html.html
  packages/demo-html/public/behavioral-html/load-html.html
  packages/demo-html/public/behavioral-html/scroll-html.html
  packages/demo-html/public/behavioral-html/time-html.html
  packages/demo-html/public/behavioral-js/exit-js.html
  packages/demo-html/public/behavioral-js/load-js.html
  packages/demo-html/public/behavioral-js/scroll-js.html
  packages/demo-html/public/behavioral-js/time-js.html
  packages/demo-html/public/callbacks.html
  packages/demo-html/public/chat.html
  packages/demo-html/public/client-side.html
  packages/demo-html/public/popover-html.html
  packages/demo-html/public/popover-js.html
  packages/demo-html/public/popup-html.html
  packages/demo-html/public/popup-js.html
  packages/demo-html/public/reload-event.html
  packages/demo-html/public/sidetab-html.html
  packages/demo-html/public/sidetab-js.html
  packages/demo-html/public/slider-html.html
  packages/demo-html/public/slider-js.html
  packages/demo-html/public/widget-html.html
  packages/demo-html/public/widget-inline.html
  packages/demo-html/public/widget-js.html
  packages/demo-html/public/widget-sandbox.html
  packages/demo-nextjs/pages/_app.js
  packages/demo-nextjs/pages/popover.js
  packages/demo-nextjs/pages/slider.js
  packages/demo-nextjs/pages/vanilla.js
  packages/demo-react/src/App.js
  packages/demo-webpack/src/index.js
  packages/embed/e2e/spec/functional/reload.spec.ts
Labels: size/m

#415 fix(DIST-1421): Update README
  README.md
Labels: size/xs

#416 feat(DIST-1336): Add warning for non https websites
  packages/embed/src/css/includes/_http-banner.scss
  packages/embed/src/css/popover.scss
  packages/embed/src/css/popup.scss
  packages/embed/src/css/sidetab.scss
  packages/embed/src/css/slider.scss
  packages/embed/src/css/widget.scss
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-popup/create-popup.ts
  packages/embed/src/factories/create-sidetab/create-sidetab.ts
  packages/embed/src/factories/create-slider/create-slider.ts
  packages/embed/src/factories/create-widget/elements/build-widget.ts
  packages/embed/src/utils/create-http-warning-banner.spec.ts
  packages/embed/src/utils/create-http-warning-banner.ts
  packages/embed/src/utils/index.ts
Labels: size/m

#420 fix(DIST-1431): Allow camera and mic for iframe
  packages/embed/package.json
  packages/embed/src/utils/create-iframe/create-iframe.spec.ts
  packages/embed/src/utils/create-iframe/create-iframe.ts
Labels: size/xs

#423 feat(TYP-6029): Change CSS classnames prefixes
  packages/embed-react/src/components/inline-style.spec.tsx
  packages/embed/e2e/spec/functional/behavioral-popup.spec.ts
  packages/embed/e2e/spec/functional/callbacks.spec.ts
  packages/embed/e2e/spec/functional/chat.spec.ts
  packages/embed/e2e/spec/functional/client-side.spec.ts
  packages/embed/e2e/spec/functional/popover.spec.ts
  packages/embed/e2e/spec/functional/popup.spec.ts
  packages/embed/e2e/spec/functional/sidetab.spec.ts
  packages/embed/e2e/spec/functional/slider.spec.ts
  packages/embed/e2e/spec/functional/widget.spec.ts
  packages/embed/e2e/spec/visual/mobile.spec.ts
  packages/embed/src/css/popover.scss
  packages/embed/src/css/popup.scss
  packages/embed/src/css/sidetab.scss
  packages/embed/src/css/slider.scss
  packages/embed/src/css/widget.scss
  packages/embed/src/factories/create-popover/create-popover.spec.ts
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-popover/notification-days.ts
  packages/embed/src/factories/create-popup/create-popup.spec.ts
  packages/embed/src/factories/create-popup/create-popup.ts
  packages/embed/src/factories/create-sidetab/create-sidetab.spec.ts
  packages/embed/src/factories/create-sidetab/create-sidetab.ts
  packages/embed/src/factories/create-slider/create-slider.spec.ts
  packages/embed/src/factories/create-slider/create-slider.ts
  packages/embed/src/factories/create-widget/create-widget.ts
  packages/embed/src/factories/create-widget/elements/build-widget.spec.ts
  packages/embed/src/factories/create-widget/elements/build-widget.ts
  packages/embed/src/utils/create-iframe/get-form-event-handler.ts
Labels: size/m

#422 fix(DIST-1432): Prevent text from being hidden by ellipsis in side tab
  packages/embed/src/css/sidetab.scss
Labels: size/xs
