Repository Typeform/embed, pull requests merged in 2021-05, with the labels that each got.

#233 test(DIST-827): Button color
  packages/embed/src/factories/create-popover/create-popover.spec.ts
  packages/embed/src/factories/create-popover/create-popover.ts
Labels: size/s

#235 feat(DIST-828): Widget, popover, sidetab sizes params
  packages/demo-html/public/sidetab-js.html
  packages/embed/src/base/index.ts
  packages/embed/src/base/sizeable-options.ts
  packages/embed/src/factories/create-popover/create-popover.spec.ts
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-popover/popover-options.ts
  packages/embed/src/factories/create-popup/create-popup.ts
  packages/embed/src/factories/create-popup/popup-options.ts
  packages/embed/src/factories/create-sidetab/create-sidetab.spec.ts
  packages/embed/src/factories/create-sidetab/create-sidetab.ts
  packages/embed/src/factories/create-sidetab/sidetab-options.ts
  packages/embed/src/factories/create-slider/create-slider.ts
  packages/embed/src/factories/create-slider/slider-options.ts
  packages/embed/src/factories/create-widget/create-widget.ts
  packages/embed/src/factories/create-widget/elements/build-widget.spec.ts
  packages/embed/src/factories/create-widget/elements/build-widget.ts
  packages/embed/src/factories/create-widget/widget-options.ts
  packages/embed/src/initializers/build-options-from-attributes.spec.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
  packages/embed/src/initializers/initialize-popovers.ts
  packages/embed/src/initializers/initialize-popups.ts
  packages/embed/src/initializers/initialize-sidetabs.ts
  packages/embed/src/initializers/initialize-sliders.ts
  packages/embed/src/utils/index.ts
  packages/embed/src/utils/set-element-size.spec.ts
  packages/embed/src/utils/set-element-size.ts
Labels: size/m

#237 feat(DIST-945): Allow sandbox mode for embedded forms
  packages/demo-html/public/widget-sandbox.html
  packages/embed/README.md
  packages/embed/src/base/url-options.ts
  packages/embed/src/initializers/build-options-from-attributes.spec.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
  packages/embed/src/utils/build-iframe-src.ts
  packages/embed/src/utils/build-iframe.src.spec.ts
Labels: size/s

#240 feat(DIST-826): Add tooltip for popover embed
  packages/demo-html/public/popover-html.html
  packages/embed/README.md
  packages/embed/src/css/popover.scss
  packages/embed/src/factories/create-popover/create-popover.spec.ts
  packages/embed/src/factories/create-popover/create-popover.ts
  packages/embed/src/factories/create-popover/popover-options.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
Labels: size/m

#241 chore(DIST-828): Embed docs update
  packages/embed/README.md
Labels: size/xs

#244 feat(DIST-752): Release v0 to CDN on relevant changes only
  .github/workflows/release.yml
  .releaserc
  package.json
  yarn.lock
Labels: size/m

#243 feat(DIST-752): Release to CDN on relevant changes only
  .github/workflows/release.yml
  .releaserc
  packages/embed/package.json
Labels: size/s

#246 chore: [SETI-1159] :construction_worker: add ci standard workflow
  .github/workflows/ci-standard-checks.yml
  .github/workflows/secrets-scan.yml
Labels: size/s

#251 feat(DIST-979): Disable tracking in sandbox mode
  packages/embed/README.md
  packages/embed/src/utils/build-iframe-src.ts
  packages/embed/src/utils/build-iframe.src.spec.ts
Labels: size/s
