Repository Typeform/embed, pull requests merged in 2022-02, with the labels that each got.

#463 feat(DIST-1530): Automatically resize widget height based on current question
  .github/workflows/pull-request-next.yml
  docs/callbacks.md
  docs/configuration.md
  packages/demo-html/public/callbacks.html
  packages/demo-html/public/widget-autoresize.html
  packages/embed/README.md
  packages/embed/src/base/actionable-options.ts
  packages/embed/src/base/sizeable-options.ts
  packages/embed/src/factories/create-widget/create-widget.ts
  packages/embed/src/initializers/build-options-from-attributes.spec.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
  packages/embed/src/utils/create-iframe/create-iframe.spec.ts
  packages/embed/src/utils/create-iframe/create-iframe.ts
  packages/embed/src/utils/create-iframe/get-form-event-handler.spec.ts
  packages/embed/src/utils/create-iframe/get-form-event-handler.ts
Labels: size/m

#465 feat(DIST-1486): Allow full url in iframe src
  .github/workflows/pull-request-next.yml
  packages/embed/src/utils/build-iframe-src.ts
  packages/embed/src/utils/build-iframe.src.spec.ts
Labels: size/s

#466 feat(DIST-1482): Specify redirect target
  docs/configuration.md
  packages/embed/README.md
  packages/embed/src/base/url-options.ts
  packages/embed/src/initializers/build-options-from-attributes.spec.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
  packages/embed/src/utils/build-iframe-src.ts
Labels: size/m

#472 fix(TYP-6436): Image contain for sidetab icon
  packages/embed/src/css/sidetab.scss
Labels: size/xs

#473 chore(DIST-1493): Add workflow that auto closes issues
  .github/workflows/auto-close-issue.yml
Labels: size/s

#475 feat(DIST-1070): Callback for ending button click
  docs/configuration.md
  packages/demo-html/public/callbacks.html
  packages/embed/README.md
  packages/embed/src/base/actionable-options.ts
  packages/embed/src/initializers/build-options-from-attributes.ts
  packages/embed/src/utils/create-iframe/create-iframe.ts
  packages/embed/src/utils/create-iframe/get-form-event-handler.spec.ts
  packages/embed/src/utils/create-iframe/get-form-event-handler.ts
Labels: size/s

#476 fix(DIST-1550): Center custom icon in popover button
  packages/embed/src/css/popover.scss
  packages/embed/src/factories/create-popover/create-popover.ts
Labels: size/xs

#477 fix(DIST-1549): Close button color on desktop
  packages/embed/src/css/includes/_close.scss
  packages/embed/src/css/includes/_mobile.scss
Labels: size/s
