Repository Typeform/embed, pull requests merged in 2025-05, with the labels that each got.

#688 build(PLT-816): Update workflows to use temporary credentials
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: 1 min review

#689 feat(PLT-1578): eu region option for live embed routing
  .github/workflows/pull-request.yml
  packages/demo-html/public/live-embed-eu.html
  packages/embed/e2e/spec/functional/live-embed-eu.cy.ts
  packages/embed/src/constants.ts
  packages/embed/src/initializers/initialize-live-embeds.ts
  packages/embed/src/live-embed/fetch-live-embed.ts
Labels: 5 min review

#690 feat(PLT-1578): EU region option for embed and embed-react
  docs/configuration.md
  packages/demo-nextjs/pages/widget-eu.tsx
  packages/demo-nextjs/shared/constants.ts
  packages/demo-nextjs/shared/menu.tsx
  packages/embed-react/tsconfig.json
  packages/embed/src/base/url-options.ts
  packages/embed/src/constants.ts
  packages/embed/src/utils/build-iframe-src.spec.ts
  packages/embed/src/utils/build-iframe-src.ts
Labels: 10 min review
